[package]
name = "j_r_r_token"
version = "0.1.0"
edition = "2021"
authors = ["Logan Bresnahan <loganbbres@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6" }
tiktoken-rs = { version= "0.7" }
