name: Ruby Gem CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:
  test:
    if: github.event_name != 'release'
    name: Test on ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, ubuntu-22.04-arm]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test
        run: bundle exec rake

  ci-data:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: oxidize-rb/actions/fetch-ci-data@main
        id: fetch
        with:
          supported-ruby-platforms: |
            exclude: ['x64-mingw32', 'x64-mingw-ucrt']
          stable-ruby-versions: |
            exclude: [head]

  # Build and publish generic ruby gem (fallback)
  ruby-gem:
    name: Build and publish generic ruby gem
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Build gem
        run: gem build *.gemspec
      - name: Publish to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          echo ":rubygems_api_key: $RUBYGEMS_API_KEY" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem push *.gem

  cross-gem:
    name: Compile native gem for ${{ matrix.platform }}
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: ci-data
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - uses: oxidize-rb/actions/cross-gem@v1
        id: cross-gem
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: ${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions, ',') }}
          required-ruby-version: '>= 2.7.0'
      - name: Publish to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          echo ":rubygems_api_key: $RUBYGEMS_API_KEY" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem push ${{ steps.cross-gem.outputs.gem-path }}
