name: Build and Test Gem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # We start with 2.7 based on your .gemspec requirement.
        # This matrix will create a job for each OS and each Ruby version.
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches gems

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Compile native extension (macOS)
      if: runner.os == 'macOS'
      run: bundle exec rake compile

    - name: Compile native extension (Linux & Windows)
      if: runner.os != 'macOS'
      run: bundle exec rake cross-compile

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        # Create a unique artifact name for each job
        name: ru_token-${{ runner.os }}-${{ matrix.ruby }}
        path: |
          lib/ru_token/**/*.so
          lib/ru_token/**/*.dylib
          lib/ru_token/**/*.dll

  release:
    name: Create Release and Publish Gem
    needs: build # This job will only run if all 'build' jobs succeed
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') # Only run on version tags like v0.1.0

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Use a recent Ruby for the release packaging
        bundler-cache: true

    - name: Download all compiled artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts # Download all artifacts into an 'artifacts' directory

    - name: Organize artifacts
      run: |
        mkdir -p lib
        # The find command will locate all downloaded artifacts and copy them
        # into the current directory structure, preserving their parent folders.
        find artifacts -type f -exec cp --parents -t . {} +

    - name: Build Gem
      run: gem build ru_token.gemspec

    - name: Publish to RubyGems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir -p $HOME/.gem
        echo ":rubygems_api_key: $RUBYGEMS_API_KEY" > $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        gem push *.gem
