name: Build and Test Gem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # We only need ubuntu and macos for the build jobs.
        # The ubuntu runner will cross-compile for Windows.
        os: [ubuntu-latest, macos-latest]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Compile native extension (macOS)
      if: runner.os == 'macOS'
      run: bundle exec rake compile

    - name: Cross-compile extensions (Linux)
      if: runner.os == 'Linux'
      # This one command builds for Linux and Windows targets
      run: bundle exec rake cross-compile

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ru_token-${{ runner.os }}-${{ matrix.ruby }}
        path: |
          lib/ru_token/**/*.so
          lib/ru_token/**/*.dylib
          lib/ru_token/**/*.dll

  release:
    name: Create Release and Publish Gem
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Download all compiled artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Organize artifacts
      run: |
        mkdir -p lib
        find artifacts -type f -exec cp --parents -t . {} +

    - name: Build Gem
      run: gem build ru_token.gemspec

    - name: Publish to RubyGems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir -p $HOME/.gem
        echo ":rubygems_api_key: $RUBYGEMS_API_KEY" > $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        gem push *.gem
